name: Build
on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'dev'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_release:
        description: 'Test release?'
        required: true
        default: 'false'

jobs:
  build:
    name: Build
    runs-on: macos-11
    strategy:
      matrix:
        arch: [arm64]
        platform: [macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: ls
        run: |
          ls -lta

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        #env:
          # These values are used for auto updates signing
          #APPLE_ID: ${{ secrets.APPLE_ID }}
          #APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          #CSC_LINK: ${{ secrets.CSC_LINK }}
          #CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder --mac
