name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        arch: [arm64]
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v1

      - name: Install Node and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install better-sqlite3
        run: |
          git clone https://github.com/JoshuaWise/better-sqlite3 && \
          cd better-sqlite3 && \
          npm install --ignore-scripts && \
          npx prebuild  -r electron -t 16.0.4
          cp prebuilds/better-sqlite3-v7.4.5-electron-v99-darwin-arm64.tar.gz /Users/runner/.npm/_prebuilds/dad20d-better-sqlite3-v7.4.5-electron-v99-darwin-arm64.tar.gz

      - name: Install dependencies
        run: |
          npm install

      - name: Publish releases
        env:
          # These values are used for auto updates signing
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASS: ${{ secrets.APPLE_ID_PASS }}
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run postinstall
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
